### ISSUE TITLE
This is why we keep the source to things like this *private*.

### ISSUE THREAD

**Issue by ohemilyy** [hyd3rs/wendyhatecult.club#2]
Please stop harassing me and shookens child or you will have an lawsuit from Wendy LTD

Thanks
Emily

**Comment by hyd3rs** [comment]
kellytoy is the parent of wendy, not you and shooken.

cheers,
danningtonsystems ltd

**Comment by ohemilyy** [comment]
Wendy is an apple green frog with a cream colored belly. Her eyes sit on top of her head, and are black rimmed in white. She has prominent nostrils above her smiling mouth, and a pale pink blush on her cheeks. Welcome Wendy! Wendy's birthday is May 10, meaning her SquishScope sign is a Taurus. You can always find her out on the basketball court (she won the MVP award last year) or in the science lab, since chemistry is her favorite subject. She wants to be a famous scientist when she grows up and likes to paint pictures of her inventions. She's an all around green gal, and is also very eco-friendly, always doing her part to clean up her community. Her favorite food is sushi, especially the avocado rolls and one of her other favorite hobbies includes gardening with her family!

**Comment by hyd3rs** [comment]
I JUST CLOSED THIS ISSUE I'M GOING TO LOCK IT NOW

**Comment by ohemilyy** [comment]
NO
